accounts/urls.py
from django.urls import path
from accounts import views
from accounts.views import signup



urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', signup, name='signup'),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect


def redirect_to_home(request):
    return redirect("home")


urlpatterns = [
    path("", redirect_to_home),
    path("admin/", admin.site.urls),
    path('receipts/', include('receipts.urls')),
    path('accounts/', include('accounts.urls')),
]

receipts/urls.py
from django.urls import path
from receipts import views


urlpatterns = [
     path('', views.receipt_list, name='home'),
     path('create/', views.create_receipt, name='create_receipt'),
     path('categories/', views.category_list, name='category_list'),
     path('accounts/', views.account_list, name='account_list'),
     path('categories/create/', views.create_expense_category, name='create_category'),
     path('accounts/create/', views.create_account, name='create_account'),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        User,
        related_name="categories",
        on_delete=models.CASCADE,
    )


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        User,
        related_name="accounts",
        on_delete=models.CASCADE,
    )


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(
        max_digits=10,
        decimal_places=3,
    )
    tax = models.DecimalField(
        max_digits=10,
        decimal_places=3,

    )
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="receipts",
    )
    category = models.ForeignKey(
        "ExpenseCategory",
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    account = models.ForeignKey(
        "Account",
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True,
    )

accounts/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput)


class SignupForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirmation = forms.CharField(widget=forms.PasswordInput)

receipts/forms.py
from django import forms
from receipts.models import Receipt, ExpenseCategory, Account

class ReceiptForm(forms.ModelForm):
    class Meta:
        model = Receipt
        fields = ['vendor', 'total', 'tax', 'date', 'category', 'account']


class ExpenseCategoryForm(forms.ModelForm):
    class Meta:
        model = ExpenseCategory
        fields = ['name']

class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['name', 'number']

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from accounts.forms import LoginForm, SignupForm
from django.contrib.auth.models import User

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect('home')
    else:
        form = LoginForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('login')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            password_confirmation = form.cleaned_data['password_confirmation']

            if password == password_confirmation:
                user = User.objects.create_user(username=username, password=password)
                login(request, user)
                return redirect('home')
            else:
                form.add_error('password_confirmation', "The passwords do not match.")
    else:
        form = SignupForm()
    context = {
        "form": form,
    }

    return render(request, 'accounts/signup.html', context)

receipts/views.py
from django.shortcuts import render, redirect
from receipts.models import Receipt, ExpenseCategory, Account, Receipt
from django.contrib.auth.decorators import login_required
from receipts.forms import ReceiptForm, ExpenseCategoryForm, AccountForm
# Create your views here.

@login_required(login_url='/accounts/login/')
def receipt_list(request):
    receipts = Receipt.objects.filter(purchaser=request.user)
    return render(request, 'receipts/list.html', {'receipts': receipts})

@login_required
def create_receipt(request):
    if request.method == 'POST':
        form = ReceiptForm(request.POST)
        if form.is_valid():
            receipt = form.save(commit=False)
            receipt.purchaser = request.user
            receipt.save()
            return redirect('home')
    else:
        form = ReceiptForm()

    return render(request, 'receipts/create.html', {'form': form})


@login_required
def category_list(request):
    categories = ExpenseCategory.objects.filter(owner=request.user)
    return render(request, 'categories/list.html', {'categories': categories})


@login_required
def account_list(request):
    accounts = Account.objects.filter(owner=request.user)
    return render(request, 'accounts/list.html', {'accounts': accounts})


@login_required
def create_expense_category(request):
    if request.method == 'POST':
        form = ExpenseCategoryForm(request.POST)
        if form.is_valid():
            expense_category = form.save(commit=False)
            expense_category.owner = request.user
            expense_category.save()
            return redirect('category_list')
    else:
        form = ExpenseCategoryForm()

    return render(request, 'categories/create.html', {'form': form})


@login_required
def create_account(request):
    if request.method == 'POST':
        form = AccountForm(request.POST)
        if form.is_valid():
            account = form.save(commit=False)
            account.owner = request.user
            account.save()
            return redirect('account_list')
    else:
        form = AccountForm()

    return render(request, 'accounts/create.html', {'form': form})

accounts/templates/accounts/list.html
{% extends 'base.html' %}

{% block content %}
<main>
        <table>
            <tr>
                <th>Name</th>
                <th>Number</th>
                <th>Number of receipts</th>
            </tr>
            {% for account in accounts %}
                <tr>
                    <td>{{ account.name }}</td>
                    <td>{{ account.number }}</td>
                    <td>{{ account.receipt_set.count }}</td>
                </tr>
            {% endfor %}
        </table>
            </main>


{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
        <div>
            <h1>Login</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Login</button>
            </form>
        </div>
        {% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <div>
    <h1>Signup</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Signup</button>
    </form>
  </div>
{% endblock %}

accounts/templates/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta http-equiv="=X-UA-Compatible" content="IE=egde">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Accounts</title>
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

receipts/templates/accounts/create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>Create Account</h1>
            <form method="post">
                {% csrf_token %}  
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
{% endblock %}

receipts/templates/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta http-equiv="=X-UA-Compatible" content="IE=egde">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Receipt List</title>
</head>
<header>
    <nav>
        <ul>
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'signup' %}">Signup</a></li>
            <li><a href="{% url 'create_receipt' %}">New Receipt</a></li>
            <li><a href="{% url 'create_category' %}">New Expense Category</a></li>
            <li><a href="{% url 'category_list' %}">All Categories</a></li>
            <li><a href="{% url 'create_account' %}">New Account</a></li>
            <li><a href="{% url 'account_list' %}">All Accounts</a></li>
</nav>
</header>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

receipts/templates/categories/create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>Create Category</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}  {# Render the form fields as paragraphs #}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
{% endblock %}

receipts/templates/categories/list.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <table>
            <tr>
                <th>Name</th>
                <th>Number of receipts</th>
            </tr>
            {% for category in categories %}
                <tr>
                    <td>{{ category.name }}</td>
                    <td>{{ category.receipt_set.count }}</td>
                </tr>
            {% endfor %}
        </table>
    </main>
{% endblock %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}

{% block content %}


    <main>
        <div>
            <h1>Create Receipt</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
{% endblock %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}

{% block content %}
        <main>
            <h1>My Receipts</h1>
            <table>
              <thead>
                <tr>
                  <th>Vendor</th>
                  <th>Total</th>
                  <th>Tax</th>
                  <th>Date</th>
                  <th>Category</th>
                  <th>Account</th>
                </tr>
              </thead>
              <tbody>
                {% for receipt in receipts %}
                  <tr>
                    <td>{{ receipt.vendor }}</td>
                    <td>{{ receipt.total }}</td>
                    <td>{{ receipt.tax }}</td>
                    <td>{{ receipt.date|date:"m/d/y" }}</td>
                    <td>{{ receipt.category.name }}</td>
                    <td>{{ receipt.account.name }}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </main>
{% endblock %}